# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Smart Home CI
run-name: ${{ github.actor }} is running Smart Home CI ðŸš€
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Commands - build and push 
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: micro/commands
          push: true
          tags: ghcr.io/maxbolgarin/architecture-sprint-3/commands:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Telemetry - build and push 
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: micro/telemetry
          push: true
          tags: ghcr.io/maxbolgarin/architecture-sprint-3/telemetry:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Monolith - build and push 
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: smart-home-monolith
          push: true
          tags: ghcr.io/maxbolgarin/architecture-sprint-3/monolith:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
